import Link from "next/link";
import { capabilities, experience } from "@/content/resume";

export default function ResumePage() {
  return <main className="page-shell pb-24 pt-8 md:pb-40">
    <nav className="flex items-center justify-between border-b hairline pb-5 text-sm"><Link href="/">← Portfolio</Link><a href="mailto:yanciesaludo14@gmail.com">Email me ↗</a></nav>
    <header className="grid gap-10 pb-20 pt-16 md:grid-cols-[1.3fr_.7fr] md:pb-28"><div><p className="text-sm uppercase tracking-[.16em] text-black/45">Yancie Troy Saludo</p><h1 className="mt-6 text-[clamp(3.6rem,6.5vw,6rem)] leading-[.91] tracking-[-.04em]">Product designer<br/><span className="serif">&amp; product builder.</span></h1></div><p className="self-end text-lg leading-relaxed text-black/60">I take B2B SaaS and consumer-mobile products from problem definition through interface systems and production. Based in Rizal, Philippines and working remotely.</p></header>
    <section className="grid gap-10 border-t hairline py-16 md:grid-cols-[.55fr_1.45fr]"><h2 className="text-sm uppercase tracking-[.16em] text-black/45">Independent products</h2><div className="space-y-12"><article><h3 className="text-4xl tracking-[-.04em]">GroceryBudget</h3><p className="mt-3 text-sm text-black/45">Founder · Product Designer · Builder · 2025—Now</p><p className="mt-5 max-w-[65ch] text-lg leading-relaxed text-black/62">Designed and shipped an offline-first grocery budgeting app for iOS and Android using React Native, Expo, TypeScript, Firebase, and NativeWind. Owns product decisions, UX/UI, implementation, analytics, monetization, releases, and customer feedback.</p></article><article><h3 className="text-4xl tracking-[-.04em]">Fifi</h3><p className="mt-3 text-sm text-black/45">Founder · Product Designer · Builder · 2026—Now</p><p className="mt-5 max-w-[65ch] text-lg leading-relaxed text-black/62">Designed and shipped an iOS wake-up-call alarm using Expo, Swift, AlarmKit, Live Activities, Firebase, RevenueCat, and PostHog. Built the product around offline reliability, character-led interaction, and a personalized morning briefing.</p></article></div></section>
    <section className="grid gap-10 border-t hairline py-16 md:grid-cols-[.55fr_1.45fr]"><h2 className="text-sm uppercase tracking-[.16em] text-black/45">Experience</h2><div>{experience.map(item => <article key={item.company} className="border-b hairline pb-10 pt-10 first:pt-0"><div className="flex flex-wrap items-baseline justify-between gap-3"><h3 className="text-3xl tracking-[-.04em]">{item.company} · {item.role}</h3><span className="text-sm text-black/45">{item.period}</span></div><p className="mt-5 max-w-[70ch] text-lg leading-relaxed text-black/62">{item.summary}</p></article>)}</div></section>
    <section className="grid gap-10 border-y hairline py-16 md:grid-cols-[.55fr_1.45fr]"><h2 className="text-sm uppercase tracking-[.16em] text-black/45">Capabilities</h2><div className="flex flex-wrap gap-x-3 gap-y-2">{capabilities.map((capability, index) => <span key={capability} className="text-[clamp(1.8rem,3vw,3.2rem)] tracking-[-.04em]">{capability}{index < capabilities.length - 1 && <span className="ml-3 text-black/20">/</span>}</span>)}</div></section>
  </main>;
}
